n = nuke.root()
tab = nuke.Tab_Knob('test1','test1')
text = nuke.Text_Knob('text','text')
e_knob = nuke.Enumeration_Knob('e_knob','e_knob',['value1', 'value2', 'value3'])
tab2 = nuke.Tab_Knob('test2','test2')
text2 = nuke.Text_Knob('text2','text2')
e_knob2 = nuke.Enumeration_Knob('e_knob2','e_knob2',['value1', 'value2', 'value3'])
tab3 = nuke.Tab_Knob('test3','test3')

n.addKnob(tab)
n.addKnob(text)
n.addKnob(e_knob)
n.addKnob(tab2)
n.addKnob(text2)
n.addKnob(e_knob2)
n.addKnob(tab3)